### ISSUE TITLE
System Theme

### ISSUE THREAD

**Issue by SuperStormer** [AnimeThemes/animethemes-web#134]
Kind of a minor feature request, but:
Instead of just light or dark theme, add an option that respects the system setting for color scheme (eg. check `window.matchMedia('(prefers-color-scheme: dark)').matches`)

**Comment by ManuelDevelopment** [comment]
Hey, this feature is now available on our [staging system](https://staging.animethemes.moe/wiki).

If it's not already set, you can now change your color theme setting to "System" on your [profile page](https://staging.animethemes.moe/wiki/profile).

Let us know, if there's anything we can improve. Otherwise we try to push this to production as soon as possible.
