### ISSUE TITLE
Page crashes on some iOS devices

### ISSUE THREAD

**Issue by ManuelDevelopment** [AnimeThemes/animethemes-web#71]
Because iOS has lacking support for WebM ([but is beginning to do something about it](https://caniuse.com/webm)) the page can crash on those devices. It would probably be better to show some sort of warning instead.

**Comment by Felghana** [comment]
On the latest version (ios 15) that come out last week apple is a bit less useless so the website does crash anymore. Still can't play the webms  from the page in the browser though. 

If the link could displayed somewhere on the page then iOS users could open the webm in video player such as VLC. 

iOS 15 actually supports webm video in limited contexts (https://commons.wikimedia.org/wiki/File:Schlossbergbahn.webm) actually  plays the VP9 encoded version on  iOS using the JavaScript player, but not native player.  i.e. if the user requests the desktop version of that Wikimedia page it actually plays correctly in browser. Not sure what differences causes the wikimedia webm player to work on iOS and animethemes  player not to work. 

On the old Reddit wiki version, since the video links were available in a href on the page I  could on IOS, convert the links on the page to use [vlc-x-callback://](https://wiki.videolan.org/Documentation:IOS/#x-callback-url) using some JavaScript to open each link in VLC. 

<details>
  <summary>JavaScript to convert webm links to open with VLC on iOS </summary>
  
```
javascript:(function()%7Bvar%20elems%20%3D%20document.getElementsByTagName('a')%3Bvar%20tests%20%3D%20%5B%22http%3A%2F%2Fweb.archive.org%2F%22%2C%20%22https%3A%2F%2Fmy.mixtape.moe%2F%22%2C%20%22https%3A%2F%2Fanimethemes.moe%2F%22%5D%3Bfor%20(var%20i%20%3D%200%3B%20i%20%3C%20elems.length%3B%20i%2B%2B)%7Bfor%20(var%20j%20%3D%200%3B%20j%20%3C%20tests.length%3B%20j%2B%2B)%20%7Bif%20(elems%5Bi%5D%5B'href'%5D.startsWith(tests%5Bj%5D))%7Belems%5Bi%5D%5B'href'%5D%20%3D%20'vlc-x-callback%3A%2F%2Fx-callback-url%2Fstream%3Furl%3D'%20%2B%20elems%5Bi%5D%5B'href'%5D%7D%7D%7D%7D)()
```
</details>

**Comment by ManuelDevelopment** [comment]
Thanks for the helpful tips. 

The crash on the video page was actually unrelated to the WebM videos. It was caused by iOS browsers not supporting the [MediaSession API](https://caniuse.com/mdn-api_mediasession) which I use for playback information, like when you adjust your volume on Windows you can see the title of the currently playing song. They released support for this API like last week, which is probably why the crash was fixed for you. I fixed the crash for all devices by only enabling this feature when it's supported.

I couldn't watch the video you linked on an iPad I had available to test. For the case that WebM videos aren't supported by the browser I now display more helpful information. I also included the VLC callback link you provided. You can now choose between "Play in VLC" and "Download" if a video is not playable. For proper support we have to wait for Apple to probably support WebM I guess.

Fixed with https://github.com/AnimeThemes/animethemes-web/commit/190e02a3848878f185e9be5e3dd0041763e2077e. Closing.

**Comment by Felghana** [comment]
Wonderful the open in VLC button works great on both an iPhone and iPad both using ios 15. 

If you are interested here a picture of the Wikimedia page playing the webm on an iPad Pro. Maybe the support of webm depends on the model?
![181BEC35-9080-4E99-8E1F-D083E32B57F7](https://user-images.githubusercontent.com/1128514/135002595-8418abbd-e8cf-44fb-986e-6a1d516f175e.jpeg)

The VLC button is more then good enough for me to play the video on iOS, thanks. 
`
